#!/usr/bin/env bash
# Bring up the isolated marketplace demo stack: the REAL Pulse build from this
# checkout + ClickHouse + the AMS simulator + local SMTP / webhook sinks.
#
#   bash qa/marketplace/demo-stack/up.sh
#
# Environment overrides:
#   SKIP_BUILD=1          reuse an existing $PULSE_DEMO_IMAGE instead of rebuilding
#   PULSE_DEMO_IMAGE      image tag to build/use        (default ams-pulse:mktdemo)
#   DEMO_LICENSE_TIER     none|free|pro|business|enterprise  (default none: v0.5.0+ needs no key —
#                         every feature is free; a tier mints a throwaway key for older images)
#   DEMO_PULSE_PORT       host port for the UI/API      (default 18190, 127.0.0.1 only)
#
# Writes ./.env (secrets + demo license; gitignored by the root `.env` rule) and
# ./.state/admin-token (the one-time bootstrap admin token; gitignored locally).
# Nothing here touches the prod, realams or quickstart compose projects.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../../.." && pwd)"
PROJECT="pulse-mktdemo"
COMPOSE=(docker compose -p "$PROJECT" -f "$HERE/docker-compose.demo.yml" --env-file "$HERE/.env")
export PULSE_DEMO_IMAGE="${PULSE_DEMO_IMAGE:-ams-pulse:mktdemo}"
TIER="${DEMO_LICENSE_TIER:-none}"
PORT="${DEMO_PULSE_PORT:-18190}"
STATE="$HERE/.state"
mkdir -p "$STATE"

log() { printf '[demo-stack] %s\n' "$*"; }

# ── 1. Build the image from this checkout (version-stamped like a release) ─────
if [[ "${SKIP_BUILD:-0}" != "1" ]]; then
  VERSION="$(git -C "$REPO" describe --tags --always | sed 's/^v//')"
  # Stamp "-dirty" only when the shipped code differs from HEAD; docs/qa edits do not
  # change the binary and must not mislabel it.
  if ! git -C "$REPO" diff --quiet HEAD -- server web contracts deploy/docker; then
    VERSION="${VERSION}-dirty"
  fi
  COMMIT="$(git -C "$REPO" rev-parse --short=12 HEAD)"
  BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  log "building $PULSE_DEMO_IMAGE (version $VERSION, commit $COMMIT)"
  docker build -f "$REPO/deploy/docker/pulse.Dockerfile" \
    --build-arg VERSION="$VERSION" --build-arg COMMIT="$COMMIT" --build-arg BUILD_DATE="$BUILD_DATE" \
    -t "$PULSE_DEMO_IMAGE" "$REPO"
  printf '%s\n' "$VERSION" >"$STATE/version"
fi

# ── 2. Secrets + a throwaway demo license (never the official signing key) ─────
if [[ ! -f "$HERE/.env" ]]; then
  LICENSE_LINES=""
  if [[ "$TIER" != "none" ]]; then
    log "minting a $TIER demo license with an ephemeral key pair (qa/licensegen)"
    LICENSE_LINES="$(docker run --rm -v "$REPO/qa/licensegen:/w:ro" -w /w \
      -e GOFLAGS=-buildvcs=false -e GOCACHE=/tmp/gocache golang:1.25 \
      go run . -tier "$TIER" 2>/dev/null)"
  fi
  {
    printf '# Demo stack env — generated by up.sh on %s. Local demo secrets only.\n' "$(date -u +%FT%TZ)"
    printf 'PULSE_SECRET_KEY=%s\n' "$(openssl rand -hex 32)"
    if [[ -n "$LICENSE_LINES" ]]; then
      printf '%s\n' "$LICENSE_LINES"
    fi
    printf 'PULSE_DEMO_IMAGE=%s\n' "$PULSE_DEMO_IMAGE"
    printf 'DEMO_PULSE_PORT=%s\n' "$PORT"
  } >"$HERE/.env"
  chmod 600 "$HERE/.env"
fi

# ── 3. Start ───────────────────────────────────────────────────────────────────
log "starting compose project $PROJECT"
"${COMPOSE[@]}" up -d

log "waiting for Pulse /healthz on 127.0.0.1:$PORT (mock-ams compiles on first start)"
deadline=$(( $(date +%s) + 300 ))
until curl -sf "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1; do
  if [[ $(date +%s) -ge $deadline ]]; then
    log "ERROR: Pulse did not become healthy within 300 s"; "${COMPOSE[@]}" ps; exit 1
  fi
  sleep 3
done

# ── 4. Bootstrap admin token (printed once, on first boot only) ────────────────
TOKEN="$("${COMPOSE[@]}" logs pulse 2>/dev/null | grep 'FIRST RUN' | grep -oE 'plt_[a-f0-9]+' | head -1 || true)"
if [[ -n "$TOKEN" ]]; then
  printf '%s\n' "$TOKEN" >"$STATE/admin-token"
  chmod 600 "$STATE/admin-token"
  log "admin token saved to $STATE/admin-token"
elif [[ -s "$STATE/admin-token" ]]; then
  log "re-run: keeping the existing $STATE/admin-token"
else
  log "WARNING: no bootstrap token in logs and none saved — run down.sh and start fresh"
fi

log "UI:      http://127.0.0.1:$PORT"
log "Mailpit: http://127.0.0.1:${DEMO_MAILPIT_PORT:-18125}"
log "next:    node qa/marketplace/demo-stack/seed-demo.mjs"
