#!/usr/bin/env bash
# qa/realams/scenarios/TC-S-01-twenty-publishers.sh
#
# TC-S-01: Many concurrent publishers — 20 streams stress test
#
# Assertion matrix row:
#   Steps:         1. Start 20 ffmpeg publishers at 500 kbps, prefix val-s01
#                  2. SAFETY VALVE: poll AMS broadcasts/list every 5 s for 60 s
#                     — 2 consecutive non-200 responses → stop all, FAIL with evidence
#                  3. After 60 s hold: assert AMS shows >=20 val-s01 streams broadcasting
#                  4. Assert Pulse /live/streams contains all 20 val-s01 stream IDs
#                  5. Assert pulse-realams logs have zero panics
#                  6. Stop all 20 publishers
#                  7. Assert Pulse drains to zero val-s01 streams within 60 s
#   AMS truth:     GET /LiveApp/rest/v2/broadcasts/list/0/100 → >=20 val-s01 streams broadcasting
#   Pulse assert:  all 20 IDs present; no panics; drains clean after teardown
#   Note:          Never stops ams-teststream, antmedia, or pulse-prod-* containers.
#                  Safety valve halts the scenario before AMS is overwhelmed.
#   Exit:          0 PASS | 1 FAIL | 77 SKIP (AMS unavailable at start)
#
set -euo pipefail

SCENARIO="TC-S-01"
echo "=== ${SCENARIO}: 20 concurrent publishers (stress) ===" >&2

# ── Harness bootstrap ────────────────────────────────────────────────────────────
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../harness/auth.sh
source "${_DIR}/../harness/auth.sh"
# shellcheck source=../harness/assert.sh
source "${_DIR}/../harness/assert.sh"
# shellcheck source=../harness/capture.sh
source "${_DIR}/../harness/capture.sh"
# shellcheck source=../harness/publisher.sh
source "${_DIR}/../harness/publisher.sh"

# ── Per-run identifiers ──────────────────────────────────────────────────────────
EPOCH="$(date +%s)"
PREFIX="val-s01"
COUNT=20
APP="LiveApp"

# IDs generated by start_bulk_publishers: printf '%sPREFIX%04d' n → val-s010001..val-s010020
_sid() { printf '%s%04d' "${PREFIX}" "$1"; }

EVIDENCE_DIR="${EVIDENCE_ROOT}/S18-${SCENARIO}-$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "${EVIDENCE_DIR}"
export EVIDENCE_DIR

# ── Timeline log ─────────────────────────────────────────────────────────────────
log() { printf '[%s] %s\n' "$(date -u +%H:%M:%SZ)" "$*" | tee -a "${EVIDENCE_DIR}/timeline.txt" >&2; }

# ── Internal: stop all 20 publishers ────────────────────────────────────────────
_stop_all() {
  local _si
  log "Stopping all ${COUNT} val-s01 publishers"
  for _si in $(seq 1 "${COUNT}"); do
    stop_publisher "$(_sid "${_si}")" 2>/dev/null || true
  done
}

# ── Cleanup trap ─────────────────────────────────────────────────────────────────
cleanup() {
  log "CLEANUP: stopping all ${COUNT} publishers (if still running)"
  _stop_all
}
trap cleanup EXIT

log "EPOCH=${EPOCH}  PREFIX=${PREFIX}  COUNT=${COUNT}  AMS_URL=${AMS_URL}  PULSE_URL=${PULSE_URL}"

# ── Preflight: confirm AMS is responsive before stressing it ────────────────────
log "Preflight: checking AMS responsiveness"
_preflight_code="$(curl -s -m 15 -o /dev/null -w '%{http_code}' \
  -b "${AMS_COOKIE_FILE}" \
  "${AMS_URL}/${APP}/rest/v2/broadcasts/list/0/10" 2>/dev/null || echo 000)"
if [ "${_preflight_code}" != "200" ]; then
  log "SKIP: AMS broadcasts/list returned HTTP ${_preflight_code} at preflight"
  printf 'SKIP\nPrecondition unmet: AMS not responsive (HTTP %s).\n' \
    "${_preflight_code}" > "${EVIDENCE_DIR}/verdict.txt"
  exit 77
fi
log "Preflight OK: AMS returned HTTP ${_preflight_code}"

capture_pulse "/live/overview" "pre-start"
capture_ams "/${APP}/rest/v2/broadcasts/list/0/100" "pre-start"

# ── Start 20 publishers ──────────────────────────────────────────────────────────
log "Starting ${COUNT} publishers (prefix=${PREFIX}, app=${APP}, 500 kbps)"
start_bulk_publishers "${COUNT}" "${APP}" "${PREFIX}" 500
log "All ${COUNT} publishers dispatched; beginning safety-valve hold (60 s)"

# ── Safety valve: poll AMS every 5 s for 60 s ───────────────────────────────────
# Two consecutive non-200 responses → stop all and FAIL
_sv_consecutive_fails=0
_sv_poll_count=0
_sv_max_polls=12   # 12 × 5 s = 60 s hold
_sv_triggered=false

while [ "${_sv_poll_count}" -lt "${_sv_max_polls}" ]; do
  sleep 5
  _sv_poll_count=$(( _sv_poll_count + 1 ))

  _sv_code="$(curl -s -m 15 -o /dev/null -w '%{http_code}' \
    -b "${AMS_COOKIE_FILE}" \
    "${AMS_URL}/${APP}/rest/v2/broadcasts/list/0/100" 2>/dev/null || echo 000)"

  if [ "${_sv_code}" = "200" ]; then
    _sv_consecutive_fails=0
    log "Safety valve poll ${_sv_poll_count}/${_sv_max_polls}: AMS OK (HTTP 200)"
  else
    _sv_consecutive_fails=$(( _sv_consecutive_fails + 1 ))
    log "Safety valve poll ${_sv_poll_count}/${_sv_max_polls}: AMS non-200 (HTTP ${_sv_code}) — consecutive_fails=${_sv_consecutive_fails}"
    if [ "${_sv_consecutive_fails}" -ge 2 ]; then
      log "SAFETY VALVE TRIGGERED: 2 consecutive non-200 responses from AMS — stopping all publishers"
      _sv_triggered=true
      break
    fi
  fi
done

if [ "${_sv_triggered}" = "true" ]; then
  _stop_all
  capture_ams "/${APP}/rest/v2/broadcasts/list/0/100" "safety-valve-trigger"
  capture_pulse "/live/overview" "safety-valve-trigger"
  assert_eq "ams_unresponsive" "ams_ok" \
    "${SCENARIO} SAFETY VALVE: AMS became unresponsive under 20-publisher load" || true
  scenario_verdict
  exit 1
fi

log "Safety valve hold completed (${_sv_max_polls} polls × 5 s = 60 s); AMS stayed responsive"

# ── Capture post-hold state ──────────────────────────────────────────────────────
capture_ams "/${APP}/rest/v2/broadcasts/list/0/100" "after-hold"
capture_pulse "/live/streams" "after-hold"
capture_pulse "/live/overview" "after-hold"

# ── Fetch AMS broadcast list for per-stream assertions ───────────────────────────
_ams_list="$(curl -s -m 20 \
  -b "${AMS_COOKIE_FILE}" \
  "${AMS_URL}/${APP}/rest/v2/broadcasts/list/0/100" 2>/dev/null || echo '[]')"

_ams_s01_count="$(printf '%s' "${_ams_list}" | \
  jq '[.[] | select(.streamId | startswith("val-s01"))] | length' \
  2>/dev/null || echo 0)"
log "AMS val-s01 stream count: ${_ams_s01_count} (expect >= ${COUNT})"

# ── Assert AMS shows >=20 val-s01 streams ────────────────────────────────────────
assert_gte "${_ams_s01_count}" "${COUNT}" \
  "${SCENARIO} AMS shows >=${COUNT} val-s01 streams broadcasting" || true

# ── Per-stream check: each val-s01 ID visible in AMS ────────────────────────────
log "Per-stream AMS broadcasting check for all ${COUNT} val-s01 IDs"
for _si in $(seq 1 "${COUNT}"); do
  _ssid="$(_sid "${_si}")"
  _ams_st="$(printf '%s' "${_ams_list}" | \
    jq -r --arg id "${_ssid}" \
      '.[] | select(.streamId == $id) | .status' \
    2>/dev/null | head -1 || true)"
  log "AMS ${_ssid} status=${_ams_st}"
  assert_eq "${_ams_st}" "broadcasting" \
    "${SCENARIO} AMS ${_ssid}=broadcasting" || true
done

# ── Fetch Pulse streams for per-stream check ─────────────────────────────────────
_pulse_streams="$(curl -s -m 20 \
  -H "Authorization: Bearer ${PULSE_TOKEN}" \
  "${PULSE_URL}/live/streams" 2>/dev/null || echo '{"items":[]}')"

_pulse_s01_count="$(printf '%s' "${_pulse_streams}" | \
  jq '[(.items // [])[] | select(.stream_id | startswith("val-s01"))] | length' \
  2>/dev/null || echo 0)"
log "Pulse val-s01 stream count: ${_pulse_s01_count} (expect >= ${COUNT})"

# ── Per-stream check: each val-s01 ID visible in Pulse ───────────────────────────
log "Per-stream Pulse visibility check for all ${COUNT} val-s01 IDs"
for _si in $(seq 1 "${COUNT}"); do
  _ssid="$(_sid "${_si}")"
  _pulse_st="$(printf '%s' "${_pulse_streams}" | \
    jq -r --arg id "${_ssid}" \
      '(.items // [])[] | select(.stream_id == $id) | .publisher_state' \
    2>/dev/null | head -1 || true)"
  log "Pulse ${_ssid} publisher_state=${_pulse_st}"
  assert_eq "${_pulse_st}" "publishing" \
    "${SCENARIO} Pulse ${_ssid}=publishing" || true
done

# ── Check pulse-realams logs for panics ──────────────────────────────────────────
log "Checking pulse-realams container logs for panic (expect 0)"
_panic_count="$(sg docker -c "docker logs pulse-realams-pulse-1 2>&1" \
  | grep -ci panic || true)"
log "Panic lines in pulse-realams logs: ${_panic_count}"
assert_eq "${_panic_count}" "0" \
  "${SCENARIO} pulse-realams logs: zero panic lines under 20-publisher load" || true

printf 'ams_s01_count=%s  pulse_s01_count=%s  panic_lines=%s\n' \
  "${_ams_s01_count}" "${_pulse_s01_count}" "${_panic_count}" \
  >> "${EVIDENCE_DIR}/timeline.txt"

# ── Teardown: stop all 20 publishers ────────────────────────────────────────────
log "Teardown: stopping all ${COUNT} publishers"
_stop_all
_teardown_ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
log "All publishers stopped at ${_teardown_ts}; polling for Pulse drain (≤60 s)"

# ── Poll Pulse for zero val-s01 streams (≤60 s, 5 s interval) ───────────────────
_drain_count=99
_drain_conv=999
_di=0
while [ "${_di}" -lt 12 ]; do
  sleep 5
  _drain_count="$(curl -s -m 15 \
    -H "Authorization: Bearer ${PULSE_TOKEN}" \
    "${PULSE_URL}/live/streams" 2>/dev/null \
    | jq '[(.items // [])[] | select(.stream_id | startswith("val-s01"))] | length' \
      2>/dev/null || echo 99)"
  log "Drain poll $(( _di + 1 ))/12: Pulse val-s01 count=${_drain_count}"
  if [ "${_drain_count}" = "0" ]; then
    _drain_conv=$(( (_di + 1) * 5 ))
    log "Pulse drained to zero val-s01 after ${_drain_conv} s"
    break
  fi
  _di=$(( _di + 1 ))
done

assert_eq "${_drain_count}" "0" \
  "${SCENARIO} Pulse drains to zero val-s01 streams after teardown" || true
assert_lte "${_drain_conv}" 60 \
  "${SCENARIO} val-s01 drain convergence ≤60 s" || true

capture_pulse "/live/streams" "post-drain"
capture_pulse "/live/overview" "post-drain"
printf 'teardown_ts=%s  drain_conv=%s\n' "${_teardown_ts}" "${_drain_conv}" \
  >> "${EVIDENCE_DIR}/timeline.txt"

# ── Verdict ───────────────────────────────────────────────────────────────────────
log "Writing verdict"
scenario_verdict
exit $?
